### ISSUE TITLE
[Statistic] Show Index number of Outliner in vector

### ISSUE THREAD

**Issue by kwasposer** [haniibrahim/scilab-samplestat#1]
Hello,

I have a matrix of measurement data, and one of the columns contains temperature measurements. Some of the data points contain outliers or anomalies. I’m currently using the Scilab Toolbox “samplestat” to filter out these outliers with the following function:

function [outlierfree, outlier] = ST_outlier(v, mod)
My goal is to obtain the indices of these “outliers.” I need these indices to remove the corresponding rows from the other columns in the matrix. For example, I want to align the good temperature values (outlierfree) with the time vector.

I’ve attempted to find all the outliers in the temperature vector using the find() function. However, there’s a possibility that the outlier value may occur multiple times in the temperature vector. Consequently, I end up with multiple indices for the same outlier value, and this could lead to the unintentional deletion of good data points.

Ideally, I’m looking for a function that can provide me with the indices of the outlier values.

Below, you will find a matrix:

If you plot column 8 against column 4, you will notice the presence of two outliers.

Now, let's consider the use of the "Get Index in Plot" function:

```
// If I start with ST_outlier(Matrix(:,4)); , there will be no outliers found
[outlierfree, outlier] = ST_outlier(Matrix(10:end, 4)); 

--> outlier
outlier  = 

   25.
   8.

// Obtain the index of outliers
for i = 1:size(outlier, '*')
    index(i) = find(Matrix(10:end, 4) == outlier(i));
end

// The issue arises here if the values of the outliers are found in the matrix, even if they are not outliers.

--> index  = 

   11.
   15.
```

Now, what would be the most effective way to delete all rows corresponding to these indices? For example:

```
for i = 1:size(index)
     Matrix(index(i), :) = [];
end
```

Is it possible to delete all rows if I have used struct.row1, struct.row2, and so on?

I hope this example provides clarity on my predicament.

```
79.0	5.0	182.0	6.0	80.0	377.0	95.0	0.0
79.0	5.0	182.0	8.0	80.0	377.0	96.0	0.01
79.0	5.0	182.0	12.0	80.0	377.0	97.0	0.02
79.0	5.0	182.0	20.0	80.0	377.0	98.0	0.03
79.0	5.0	183.0	25.0	80.0	377.0	99.0	0.04
79.0	5.0	183.0	32.0	80.0	377.0	0.0	0.05
79.0	5.0	183.0	40.0	80.0	377.0	1.0	0.06
79.0	5.0	183.0	50.0	80.0	377.0	2.0	0.07
79.0	5.0	183.0	62.0	80.0	377.0	3.0	0.08
79.0	5.0	185.0	75.0	80.0	377.0	4.0	0.09
79.0	5.0	185.0	88.0	80.0	377.0	5.0	0.1
79.0	5.0	185.0	100.0	80.0	377.0	6.0	0.11
79.0	5.0	185.0	101.0	80.0	377.0	7.0	0.12
79.0	5.0	185.0	101.0	80.0	377.0	8.0	0.13
79.0	5.0	185.0	101.0	80.0	377.0	9.0	0.14
79.0	5.0	185.0	100.0	80.0	377.0	10.0	0.15
79.0	5.0	185.0	102.0	80.0	377.0	11.0	0.16
79.0	5.0	185.0	102.0	80.0	377.0	12.0	0.17
79.0	5.0	185.0	102.0	80.0	377.0	13.0	0.18
79.0	5.0	185.0	25.0	80.0	377.0	14.0	0.19
79.0	5.0	183.0	100.0	80.0	377.0	15.0	0.2
79.0	5.0	183.0	105.0	80.0	377.0	16.0	0.21
79.0	5.0	183.0	105.0	80.0	377.0	17.0	0.22
79.0	5.0	183.0	8.0	80.0	377.0	18.0	0.23
79.0	5.0	183.0	102.0	80.0	377.0	19.0	0.24
79.0	5.0	185.0	101.0	80.0	377.0	20.0	0.25
79.0	5.0	185.0	101.0	80.0	377.0	22.0	0.27
79.0	5.0	183.0	101.0	80.0	377.0	23.0	0.28
79.0	5.0	183.0	100.0	80.0	377.0	24.0	0.29
79.0	5.0	183.0	102.0	80.0	377.0	26.0	0.31
79.0	5.0	183.0	102.0	80.0	377.0	27.0	0.32
79.0	5.0	183.0	102.0	80.0	377.0	28.0	0.33
79.0	5.0	183.0	102.0	80.0	377.0	29.0	0.34
79.0	5.0	183.0	102.0	80.0	377.0	30.0	0.35
79.0	5.0	183.0	103.0	80.0	377.0	31.0	0.36
79.0	5.0	183.0	103.0	80.0	377.0	32.0	0.37
79.0	5.0	185.0	103.0	80.0	377.0	33.0	0.38
79.0	5.0	183.0	101.0	80.0	377.0	35.0	0.4
79.0	5.0	183.0	105.0	80.0	377.0	36.0	0.41
79.0	5.0	183.0	105.0	80.0	377.0	37.0	0.42
79.0	5.0	183.0	105.0	80.0	377.0	38.0	0.43

```

![image|533x410](upload://81GkZf937DvpsbjQSZeptV5D8sv.png)

**Comment by haniibrahim** [comment]
Hi User,

1. Your very question: _"Is it possible to delete all rows if I used struct.row1, struct.row2 etc.?"_ **has nothing to do with my sampleSTAT toolbox** and also _"what would be the most effective way to delete all rows corresponding to these indices?"_
3. You use Matlab syntax (%, end, etc.). We are talking about the Scilab toolbox not the Octave module I also wrote?
4. The purpose of statistical outlier testing methods is not to remove data you don't like.

Anyway.

# Some important general statements first

Sorry if this sounds rude or arrogant.

> % If I start with ST_outlier(Matrix(:,4)); , there will be no outliers found

Because there are no outliers. You cannot manipulate statistical methods to get what you want! But I see a drift from point 1 to 11. Why? 

![data](https://hani-ibrahim.de/public/misc/data.png "data")

If you remove the first 9 data points, you need to explain this very well and why 1 to 9.  You cannot remove them just because you do not like them.

Because maybe there is a problem in your experimental and/or measurement setup. Take this into account.

Also choose the right statistical (outlier) tool.  For experimental measurement data, depending on the amount of data, I would only use for manageable amounts

* Dean-Dixon
* Pearson-Hartley

or with stomachache Nalimov. But this is just my opinion.

# Just the answer for removing data rows

_"...if I used struct.row1, struct.row2 ..."_ => I would not recommend that.

_"what would be the most effective way to delete all rows corresponding to these indices?"_ => I do not know a effective or elegant but a working way. Refer below.

**Both question has nothing to do with my toolbox. Please ask this kind of question in the [Scilab mailing list](https://www.scilab.org/about/community/mailing-lists]).**

Anyway, I was so kind to do your (home)work!

![Nassi-Shneiderman diagram](https://hani-ibrahim.de/public/misc/RemoveOutlierRows.png "Nassi-Shneiderman diagram")

```scilab
// Delete data rows with "outliers" with Scilab 2023.1.0

// Generate data matrix
data = [ ..
79.0	5.0	182.0	6.0	80.0	377.0	95.0	0.0
79.0	5.0	182.0	8.0	80.0	377.0	96.0	0.01
79.0	5.0	182.0	12.0	80.0	377.0	97.0	0.02
79.0	5.0	182.0	20.0	80.0	377.0	98.0	0.03
79.0	5.0	183.0	25.0	80.0	377.0	99.0	0.04
79.0	5.0	183.0	32.0	80.0	377.0	0.0	0.05
79.0	5.0	183.0	40.0	80.0	377.0	1.0	0.06
79.0	5.0	183.0	50.0	80.0	377.0	2.0	0.07
79.0	5.0	183.0	62.0	80.0	377.0	3.0	0.08
79.0	5.0	185.0	75.0	80.0	377.0	4.0	0.09
79.0	5.0	185.0	88.0	80.0	377.0	5.0	0.1
79.0	5.0	185.0	100.0	80.0	377.0	6.0	0.11
79.0	5.0	185.0	101.0	80.0	377.0	7.0	0.12
79.0	5.0	185.0	101.0	80.0	377.0	8.0	0.13
79.0	5.0	185.0	101.0	80.0	377.0	9.0	0.14
79.0	5.0	185.0	100.0	80.0	377.0	10.0	0.15
79.0	5.0	185.0	102.0	80.0	377.0	11.0	0.16
79.0	5.0	185.0	102.0	80.0	377.0	12.0	0.17
79.0	5.0	185.0	102.0	80.0	377.0	13.0	0.18
79.0	5.0	185.0	25.0	80.0	377.0	14.0	0.19
79.0	5.0	183.0	100.0	80.0	377.0	15.0	0.2
79.0	5.0	183.0	105.0	80.0	377.0	16.0	0.21
79.0	5.0	183.0	105.0	80.0	377.0	17.0	0.22
79.0	5.0	183.0	8.0	80.0	377.0	18.0	0.23
79.0	5.0	183.0	102.0	80.0	377.0	19.0	0.24
79.0	5.0	185.0	101.0	80.0	377.0	20.0	0.25
79.0	5.0	185.0	101.0	80.0	377.0	22.0	0.27
79.0	5.0	183.0	101.0	80.0	377.0	23.0	0.28
79.0	5.0	183.0	100.0	80.0	377.0	24.0	0.29
79.0	5.0	183.0	102.0	80.0	377.0	26.0	0.31
79.0	5.0	183.0	102.0	80.0	377.0	27.0	0.32
79.0	5.0	183.0	102.0	80.0	377.0	28.0	0.33
79.0	5.0	183.0	102.0	80.0	377.0	29.0	0.34
79.0	5.0	183.0	102.0	80.0	377.0	30.0	0.35
79.0	5.0	183.0	103.0	80.0	377.0	31.0	0.36
79.0	5.0	183.0	103.0	80.0	377.0	32.0	0.37
79.0	5.0	185.0	103.0	80.0	377.0	33.0	0.38
79.0	5.0	183.0	101.0	80.0	377.0	35.0	0.4
79.0	5.0	183.0	105.0	80.0	377.0	36.0	0.41
79.0	5.0	183.0	105.0	80.0	377.0	37.0	0.42
79.0	5.0	183.0	105.0	80.0	377.0	38.0	0.43
];

// Just take the whole and temp data from row 10 onwards (for whatever reason)
data1 = data (10:$,:);
temp1 = data(10:$,4);

// Obtain outliers (o) via Person-Hartley with 95% statistical confidence
[of,o]=ST_pearsonhartley(temp1,"95%");

// outlier indices
for i = 1:length(o)
    idx(i) = find(temp1 == o(i));
end

// delete outlier rows from data
// -----------------------------
// I do not know if this is efficient but it works

olFlag = %F;                     // initialize outlierflag
k = 0;                           // initialite index of result matrix
clearedData = [];                // initialize result matrix

for i=1:size(data1,"r")          // iterate over data1 rows
    for j=1:length(idx)          // iterate over outlier indices
        if i == idx(j) then      // if outlier
            olFlag = %T;
        elseif olFlag == %T then // do not overwrite a true olFlag for the current data row
            continue;
        else                     // if no outlier
            olFlag = %F
        end
    end
    if olFlag == %F then         // write or write not the data row to result matrix clearedData, dependent on the olFlag
        k = k + 1;               // increment index of result matrix
        clearedData(k,:) = data1(i,:);
    else
        olFlag = %F;             // reinitialize the olFlag to false
    end
end

// Display result matrix
disp(clearedData)
```
# Final words

Again, do not misuse statistical methods to manipulate your data or manipulate it in any other way. Your professor/boss/colleague/customer will throw this in your face. No offense.

**Comment by kwasposer** [comment]
Dear Hani,

I would like to express my sincere appreciation for your invaluable support. Please don't be upset with my concern. I was genuinely delighted to discover your package on the Atom package manager. Sometimes, it's quite convenient to make progress without delving too deep into the details.

Your "ST_outlier" function performed admirably. As I mentioned earlier, my objective was to obtain the indices of all the identified outliers. If you attempt to locate the values of the outliers within a vector or a matrix column, there's a possibility that these values may coincide with non-outlier values. Therefore, it would be ideal if you could modify your code so that it consistently provides the index whenever an outlier is detected.

```
// outlier indices
for i = 1:length(o)
    idx(i) = find(temp1 == o(i));
end
```

**How can you be sure that an outlier value o(i) is not matching with one of the outlierfree value of(j), so the idx(i) will be >1 ?**

In my example, it will find to outlier in column 4: outlier=[8 , 25]
But found() will give you 2 indices of both values.
idx(outlier(1)) = [2, 24]
idx(outlier(2)) = [5, 21]

So, would loose good values "outlierfree" in my data and besides your loop will not work, because for each outlier you'll get more than one value, which causes an error.


In order to delete outlier rows, you could just use:

```
for i = 1:length(idx)
       data1(idx(i),:)=[]
end
```

I am truly grateful for your assistance and will further explore this. Your bar graph is fantastic and significantly aids in my comprehension of how the analysis might function.

I apologize for the accidental use of the "%" symbol; it occurred while I was typing.

Once again, thank you for your time and for assisting me with my (home) work. :-)

Warm regards,
Kwas

**Comment by kwasposer** [comment]
```
data1 = data(:, 4);
````
The results for '[of, o] = ST_pearsonhartley(data1);' and '[of, o] = ST_outlier(data1);' are identical.

I have managed to obtain the indices of the outliers directly. I made a minor modification to your code in 'ST_personhartley.sci':

```
function [outlierfree, outlier, outlier_idx] = ST_pearsonhartley(v, p)

// Previous code

apifun_checklhs("ST_pearsonhartley", lhs, 1:3); // Output args

// Previous code

for i = 1:n
    q = abs((v(i) - X) / S);
    if (q > qcritval)
        outlier(j) = v(i);
        outlier_idx(j) = i;  // Index of the outlier
        j = j + 1;

        continue;
    end
    outlierfree(k) = v(i);
    k = k + 1;
end
```

This modification works perfectly!

**However, there is still a question. How can I extend 'qtable' to handle a vector with more than 1000 values?**

```
"Pearson-Hartley is only applicable for sample distributions with more than 3\n" + ..
"and fewer than 1000 values.")); 
```

```
/////////////////////////////////////////////////////////////////////////////////////////
```

I have also made changes to 'ST_outlier.sci':

Please don't be upset with me. I simply want to find a quick solution to filter my data before delving into statistics. I will certainly explore deeper if necessary, but for now, I am content with speeding up the process. Sometimes, you don't need to be an expert in everything.

My modified version of 'ST_outlier.sci' works perfectly, even though you suggest using 'ST_personhartley.sci'. Next weekend, I will attempt to understand the difference between these two functions, but perhaps you could provide some guidance on 'ST_personhartley.sci' and the 'qtable' aspect.

Here is my current solution:

```
size(measurement)  // Matrix size 1306 x 8
data = measurement(:, 4); // Only interested in finding outliers in column 4
[of, o, o_idx] = ST_outlier(data); // Find outliers and their indices in o_idx
measurement(o_idx, :) = []; // Remove all rows that match the indices in o_idx
```

**Comment by kwasposer** [comment]
Hello Harni,

I followed your great comments in the code and can dig deeper now . Thank you for your great work!!

http://www.statistics4u.info/fundstat_germ/ee_pearson_outliertest.html


What would you suggest for a dataset that is not stationary? I've actually found the ST_outlier function to be quite effective. That's one of the reasons I initiated the filtering process even when the dataset is in a stationary state.

**Comment by haniibrahim** [comment]
Hello Kwas,

> In order to delete outlier rows, you could just use:
> 
> ```scilab
> for i = 1:length(idx)
>        data1(idx(i),:)=[]
> end
> ```

Unfortunately your simple attempt to delete outlier rows do not work properly as you can see below:

```
   79.   5.   185.   75.    80.   377.   4.    0.09
   79.   5.   185.   88.    80.   377.   5.    0.1 
   79.   5.   185.   100.   80.   377.   6.    0.11
   79.   5.   185.   101.   80.   377.   7.    0.12
   79.   5.   185.   101.   80.   377.   8.    0.13
   79.   5.   185.   101.   80.   377.   9.    0.14
   79.   5.   185.   100.   80.   377.   10.   0.15
   79.   5.   185.   102.   80.   377.   11.   0.16
   79.   5.   185.   102.   80.   377.   12.   0.17
   79.   5.   185.   102.   80.   377.   13.   0.18
   79.   5.   183.   100.   80.   377.   15.   0.2 
   79.   5.   183.   105.   80.   377.   16.   0.21
   79.   5.   183.   105.   80.   377.   17.   0.22
   79.   5.   183.   8.     80.   377.   18.   0.23 // <---- outlier in row 15
   79.   5.   185.   101.   80.   377.   20.   0.25
   79.   5.   185.   101.   80.   377.   22.   0.27
   79.   5.   183.   101.   80.   377.   23.   0.28
   79.   5.   183.   100.   80.   377.   24.   0.29
   79.   5.   183.   102.   80.   377.   26.   0.31
   79.   5.   183.   102.   80.   377.   27.   0.32
   79.   5.   183.   102.   80.   377.   28.   0.33
   79.   5.   183.   102.   80.   377.   29.   0.34
   79.   5.   183.   102.   80.   377.   30.   0.35
   79.   5.   183.   103.   80.   377.   31.   0.36
   79.   5.   183.   103.   80.   377.   32.   0.37
   79.   5.   185.   103.   80.   377.   33.   0.38
   79.   5.   183.   101.   80.   377.   35.   0.4 
   79.   5.   183.   105.   80.   377.   36.   0.41
   79.   5.   183.   105.   80.   377.   37.   0.42
   79.   5.   183.   105.   80.   377.   38.   0.43
```
1. You missed one outlier line (row 15) and 
2. delete a valid data row 16:

```
79.   5.   183.   102.   80.   377.   19.   0.24
```

It is not that easy as you see. You have to take care with more than one outlier and with the indices. There  is a reason why my algorithm is that simple.

----

> ... it would be ideal if you could modify your code so that it consistently provides the index ...

Well, in general, you only have a vector of measurement data to apply this type of statistic, not a multi-dimensional matrix. And the outlier macros should only provide the outlier-free and outlier data. So I don't see the need to change the scripts. Especially since you can add this functionality with a few lines of code if needed.

But you are free to add this functionality yourself. sampleSTAT is open source and under GPL.

----

> How can you be sure that an outlier value o(i) is not matching with one of the outlierfree value of(j), so the idx(i) will be >1 ?

I do not see any problems here. That is a problem your code above has. Look at my double-for-loop code. It is not elegant but it works even with more than one outliers. You get rid of both outlier rows (values 8 & 25) and do not lose any outlier-free rows.

----

> However, there is still a question. How can I extend 'qtable' to handle a vector with more than 1000 values?

1. sampleSTAT was not made to handle this amount of data.
2. You can use the `ST_outlier(data,"sd")` test or Grubbs [1] (not part of sampleSTAT). Even Nalimov could be an option, but I do not recommend Nalimov because it tends to remove even valid data. I just added it for historical reasons. It was popular in Germany in the past. Even I used it these days.

All test have their pros and cons, based on the amount of data and their origin and how they are distributed. For example `ST_outlier(data,"iqr15")` or `ST_outlier(data,"iqr30")` has an advantage with skewed data [2]. But this is very rare in measurement data.

----

> I simply want to find a quick solution to filter my data before delving into statistics.

Well, **outlier filtering is statistics** and you have to be careful with them. You can easily distort your results by choosing the wrong outlier method or how you apply it to your data. Many people use these (outlier) tools carelessly, today.

**Outliers are not normal.** There are always reasons for them. You should always question your data (and your experimental and measurement setup) and do not carelessly apply outlier tests because it is so easy nowadays. If you have weird values in your data frequently you have a massive problem in your setup that outlier tests cannot solve. That can even mean that the valid-looking data points are not valid and can lead to wrong decisions or results. Do not use outlier tests as a routine. Question your data.

So, enough patronizing for today ;-)

[1] http://www.statistics4u.info/fundstat_eng/ee_grubbs_outliertest.html
[2] http://www.statistics4u.info/fundstat_eng/cc_outlier_tests_4sigma.html
